name: autoUpload # yml文件名

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:
jobs:
  run-autoUpload: # 任务名
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@main #采用main分支下的
      - name: Setup Node.js
        uses: actions/setup-node@v2 #安装node.js
        with:
          node-version: "18"

      - name: Install Dependency
        run: |
          npm install
      - name: npm run autoUpload
        run: |
          touch .env
          echo TENCENTCLOUD_SECRET_ID=${{ secrets.TENCENTCLOUD_SECRET_ID }} >> .env
          echo TENCENTCLOUD_SECRET_KEY=${{ secrets.TENCENTCLOUD_SECRET_KEY }} >> .env
          echo `ls -a`
          npm run autoUpload  # 要运行的js脚本，放在根目录下
      - uses: GuillaumeFalourd/git-commit-push@v1.3
        with:
          email: ${{ github.actor }}@users.noreply.github.com
          name: ${{ github.actor }}
          commit_message: auto upload
          target_branch: main
          files: __data__
          remote_repository: https://github.com/liyao1520/lol-assets
          access_token: ${{ github.token }}
          force: true
          empty: true
          tags: true
      - name: remove __data__
        run: |
          rm -rf __data__
